name: Checking Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checking:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: python-flake8
      uses: julianwachholz/flake8-action@v1.0.0
      
    - name: Mypy Check
      uses: jpetrucciani/mypy-check@0.761
     
    # TODO: run unit tests
