name: type check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checking:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Mypy Check
      uses: jpetrucciani/mypy-check@0.761
